/* Privat synk och delade familjelistor. Åtkomsten skyddas av firestore.rules. */
(()=>{
  if(!window.firebase)return;
  const firebaseConfig={apiKey:'AIzaSyB7gHnwaDCTIRrK7vE2NjkntNE4Tb60kjQ',authDomain:'todo-list-aff74.firebaseapp.com',projectId:'todo-list-aff74',storageBucket:'todo-list-aff74.firebasestorage.app',messagingSenderId:'836194978024',appId:'1:836194978024:web:5f9679bd917810f8e5e15d'};
  firebase.initializeApp(firebaseConfig);
  const auth=firebase.auth(),db=firebase.firestore(),provider=new firebase.auth.GoogleAuthProvider();
  provider.setCustomParameters({prompt:'select_account'});
  document.head.insertAdjacentHTML('beforeend','<style>.sync-card,.lists-card,.invite-card{display:grid;gap:10px;padding:12px 14px;margin:12px 0 0;border:1px solid var(--l);border-radius:15px;background:var(--t)}.sync-user{display:flex;align-items:center;gap:10px;min-width:0}.sync-user>div{min-width:0}.sync-avatar{display:grid;place-items:center;width:38px;height:38px;flex:0 0 38px;overflow:hidden;border-radius:50%;background:var(--p);font-size:1rem}.sync-avatar img{width:100%;height:100%;object-fit:cover}.sync-card b,.lists-card b,.invite-card b{display:block;font-size:.88rem}.sync-card small,.lists-card small,.invite-card small{display:block;color:var(--m);margin-top:2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.sync-email{font-size:.76rem}.side-menu .sync-card button,.side-menu .lists-card button,.side-menu .invite-card button{width:100%;margin:0;min-height:40px;white-space:nowrap;background:var(--p);color:var(--i)}.side-menu .sync-card .sync-google,.side-menu .lists-card .create-list,.invite-actions button:first-child{background:var(--v);color:#fff}.list-buttons{display:grid;gap:6px}.list-buttons button.active-list{outline:2px solid var(--v);color:var(--v)}.invite-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.member-row{display:flex;justify-content:space-between;gap:8px;align-items:center;color:var(--m);font-size:.8rem}.member-row button{width:auto!important;min-height:32px!important;padding:0 9px!important}.shared-heading{display:flex;justify-content:space-between;align-items:center;gap:8px}.shared-heading button{width:auto!important;min-height:34px!important;padding:0 9px!important}</style>');
  const syncCard=document.createElement('section');syncCard.className='sync-card';syncCard.innerHTML='<div class="sync-user"><span class="sync-avatar" id="sync-avatar">☁️</span><div><b id="sync-title">Synka mellan enheter</b><small class="sync-email" id="sync-email" hidden></small><small id="sync-status">Logga in för att se samma lista på telefon och dator.</small></div></div><button class="sync-google" id="sync-login">Fortsätt med Google</button>';
  const listsCard=document.createElement('section');listsCard.className='lists-card';listsCard.hidden=true;listsCard.innerHTML='<div class="shared-heading"><b>📋 Mina listor</b><button type="button" class="create-list">＋ Ny delad lista</button></div><div class="list-buttons" id="list-buttons"></div><div id="shared-controls" hidden><button type="button" class="share-list">👥 Bjud in med e-post</button><div id="member-list"></div></div>';
  const invitesCard=document.createElement('section');invitesCard.className='invite-card';invitesCard.hidden=true;invitesCard.innerHTML='<b>✉️ Inbjudningar</b><div id="invite-list"></div>';
  document.querySelector('#side-menu').append(listsCard,invitesCard,syncCard);
  const title=document.querySelector('#sync-title'),email=document.querySelector('#sync-email'),avatar=document.querySelector('#sync-avatar'),status=document.querySelector('#sync-status'),login=document.querySelector('#sync-login'),listButtons=document.querySelector('#list-buttons'),sharedControls=document.querySelector('#shared-controls'),memberList=document.querySelector('#member-list'),inviteList=document.querySelector('#invite-list');
  let unsubscribeState=null,unsubscribeLists=null,unsubscribeInvites=null,unsubscribeMembers=null,remoteReady=false,applyingRemote=false,lastSyncedSignature=null,lastSyncedAt=Number(localStorage.getItem('todo-last-synced-at')||0),activeList={type:'private',name:'📋 Min privata lista'};
  const plainTasks=()=>T.map(({marked,...task})=>task),privateDocument=user=>db.collection('users').doc(user.uid).collection('todo').doc('state'),sharedDocument=id=>db.collection('sharedLists').doc(id).collection('todo').doc('state'),activeDocument=user=>activeList.type==='private'?privateDocument(user):sharedDocument(activeList.id),setStatus=text=>status.textContent=text;
  function showSyncStatus(){if(!navigator.onLine){setStatus('⚠️ Ingen anslutning — synkar automatiskt senare.');return}if(!lastSyncedAt){setStatus('Synkar din lista …');return}const seconds=Math.floor((Date.now()-lastSyncedAt)/1000),when=seconds<60?'nyss':seconds<3600?`för ${Math.floor(seconds/60)} min sedan`:seconds<86400?`för ${Math.floor(seconds/3600)} tim sedan`:`för ${Math.floor(seconds/86400)} dag sedan`;setStatus(`Synkad ✓ · ${when}`)}
  function markSynced(){lastSyncedAt=Date.now();localStorage.setItem('todo-last-synced-at',String(lastSyncedAt));showSyncStatus()}
  const originalSave=save;
  async function pushState(){const user=auth.currentUser;if(!user||!remoteReady||applyingRemote)return;if(!navigator.onLine){showSyncStatus();return}const tasks=plainTasks(),signature=JSON.stringify(tasks);if(signature===lastSyncedSignature)return;setStatus('Synkar ändringar …');try{await activeDocument(user).set({tasks,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});lastSyncedSignature=signature;markSynced()}catch(error){console.warn('Kunde inte synka listan',error);setStatus('Kunde inte synka just nu — ändringarna finns kvar på enheten.')}}save=function(){originalSave();pushState()};
  function renderLists(lists=[]){listButtons.replaceChildren();[{type:'private',name:'📋 Min privata lista'},...lists].forEach(list=>{const button=document.createElement('button');button.type='button';button.textContent=list.name;button.classList.toggle('active-list',list.type===activeList.type&&list.id===activeList.id);button.onclick=()=>selectList(list);listButtons.append(button)});sharedControls.hidden=activeList.type!=='shared';if(activeList.type==='shared'){sharedControls.querySelector('.share-list').hidden=activeList.ownerId!==auth.currentUser?.uid;loadMembers()}}
  async function selectList(list){if(list.type===activeList.type&&list.id===activeList.id)return;activeList=list;remoteReady=false;lastSyncedSignature=null;if(unsubscribeState){unsubscribeState();unsubscribeState=null}renderLists(window.sharedTodoLists||[]);await startStateListener(auth.currentUser)}
  async function startStateListener(user){if(!user)return;const ref=activeDocument(user);try{const first=await ref.get();if(!first.exists&&activeList.type==='private')await ref.set({tasks:plainTasks(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});remoteReady=true;unsubscribeState=ref.onSnapshot(snapshot=>{if(!snapshot.exists){if(activeList.type==='shared')setStatus('Den här delade listan finns inte längre.');return}const cloudTasks=Array.isArray(snapshot.data().tasks)?snapshot.data().tasks:[];lastSyncedSignature=JSON.stringify(cloudTasks);applyingRemote=true;T=cloudTasks.map(task=>({...task,marked:false}));originalSave();render();applyingRemote=false;markSynced()},error=>{console.warn('Kunde inte läsa synkad lista',error);setStatus('Synkning saknar behörighet.')})}catch(error){console.warn('Kunde inte starta synkningen',error);setStatus('Kunde inte starta synkningen. Kontrollera internet och behörighet.')}}
  async function loadMembers(){if(unsubscribeMembers){unsubscribeMembers();unsubscribeMembers=null}if(activeList.type!=='shared'||activeList.ownerId!==auth.currentUser?.uid){memberList.replaceChildren();return}unsubscribeMembers=db.collection('sharedLists').doc(activeList.id).collection('members').onSnapshot(snapshot=>{memberList.replaceChildren(...snapshot.docs.map(doc=>{const row=document.createElement('div');row.className='member-row';const label=document.createElement('span');label.textContent=doc.data().email||'Familjemedlem';const remove=document.createElement('button');remove.type='button';remove.textContent='Ta bort';remove.onclick=()=>db.collection('sharedLists').doc(activeList.id).collection('members').doc(doc.id).delete();row.append(label,remove);return row}))})}
  listsCard.querySelector('.create-list').onclick=async()=>{const user=auth.currentUser,name=prompt('Namn på den delade listan, till exempel Familjen:');if(!user||!name?.trim())return;const ref=db.collection('sharedLists').doc(),list={type:'shared',id:ref.id,name:`👥 ${name.trim()}`,ownerId:user.uid};try{const batch=db.batch();batch.set(ref,{ownerId:user.uid,name:list.name,createdAt:firebase.firestore.FieldValue.serverTimestamp()});batch.set(ref.collection('todo').doc('state'),{tasks:plainTasks(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});batch.set(db.collection('users').doc(user.uid).collection('sharedLists').doc(ref.id),{name:list.name,ownerId:user.uid});await batch.commit();await selectList(list)}catch(error){console.warn('Kunde inte skapa delad lista',error);setStatus('Kunde inte skapa den delade listan. Kontrollera Firestore-reglerna.')}};
  sharedControls.querySelector('.share-list').onclick=async()=>{const user=auth.currentUser,address=prompt('Skriv Google-e-posten till personen du vill bjuda in:')?.trim().toLowerCase();if(!user||!address||!activeList.id)return;try{await db.collection('sharedLists').doc(activeList.id).collection('invites').doc(address).set({email:address,listId:activeList.id,listName:activeList.name,ownerId:user.uid,status:'pending',createdAt:firebase.firestore.FieldValue.serverTimestamp()});alert(`Inbjudan är sparad för ${address}. Personen ser den när hen loggar in i appen.`)}catch(error){console.warn('Kunde inte bjuda in',error);alert('Inbjudan kunde inte sparas. Kontrollera Firestore-reglerna.')}};
  function loadInvites(user){if(unsubscribeInvites)unsubscribeInvites();unsubscribeInvites=db.collectionGroup('invites').where('email','==',(user.email||'').toLowerCase()).onSnapshot(snapshot=>{const invites=snapshot.docs.filter(doc=>doc.data().status==='pending');invitesCard.hidden=!invites.length;inviteList.replaceChildren(...invites.map(doc=>{const data=doc.data(),row=document.createElement('div');row.innerHTML=`<small>${data.listName||'Delad lista'}</small>`;const actions=document.createElement('div');actions.className='invite-actions';const accept=document.createElement('button');accept.type='button';accept.textContent='Acceptera';accept.onclick=()=>acceptInvite(doc);const decline=document.createElement('button');decline.type='button';decline.textContent='Avböj';decline.onclick=()=>doc.ref.delete();actions.append(accept,decline);row.append(actions);return row}))},error=>console.warn('Kunde inte läsa inbjudningar',error))}
  async function acceptInvite(invite){const user=auth.currentUser,data=invite.data();if(!user)return;try{const listRef=db.collection('sharedLists').doc(data.listId),batch=db.batch();batch.update(invite.ref,{status:'accepted',recipientUid:user.uid,acceptedAt:firebase.firestore.FieldValue.serverTimestamp()});batch.set(listRef.collection('members').doc(user.uid),{email:user.email||'',joinedAt:firebase.firestore.FieldValue.serverTimestamp()});batch.set(db.collection('users').doc(user.uid).collection('sharedLists').doc(data.listId),{name:data.listName,ownerId:data.ownerId});await batch.commit();await selectList({type:'shared',id:data.listId,name:data.listName,ownerId:data.ownerId})}catch(error){console.warn('Kunde inte acceptera inbjudan',error);alert('Inbjudan kunde inte accepteras. Kontrollera Firestore-reglerna.')}}
  function loadSharedLists(user){if(unsubscribeLists)unsubscribeLists();unsubscribeLists=db.collection('users').doc(user.uid).collection('sharedLists').onSnapshot(snapshot=>{window.sharedTodoLists=snapshot.docs.map(doc=>({type:'shared',id:doc.id,...doc.data()}));renderLists(window.sharedTodoLists)},error=>console.warn('Kunde inte läsa delade listor',error))}
  login.onclick=async()=>{try{if(auth.currentUser){await auth.signOut();return}setStatus('Öppnar Google-inloggning …');await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);await auth.signInWithPopup(provider)}catch(error){console.warn('Google-inloggningen misslyckades',error);setStatus(`Inloggningen kunde inte öppnas (${error?.code||'okänt fel'}).`)}};
  auth.onAuthStateChanged(async user=>{[unsubscribeState,unsubscribeLists,unsubscribeInvites,unsubscribeMembers].forEach(unsubscribe=>unsubscribe?.());unsubscribeState=unsubscribeLists=unsubscribeInvites=unsubscribeMembers=null;remoteReady=false;lastSyncedSignature=null;activeList={type:'private',name:'📋 Min privata lista'};if(!user){title.textContent='Synka mellan enheter';email.hidden=true;avatar.replaceChildren();avatar.textContent='☁️';login.textContent='Fortsätt med Google';login.className='sync-google';listsCard.hidden=true;invitesCard.hidden=true;setStatus('Logga in för att se samma lista på telefon och dator.');return}title.textContent='Du är inloggad';email.textContent=user.email||'';email.hidden=!user.email;avatar.replaceChildren();if(user.photoURL){const image=new Image();image.src=user.photoURL;image.alt='Din profilbild';avatar.append(image)}else avatar.textContent='👤';login.textContent='Logga ut';login.className='';listsCard.hidden=false;showSyncStatus();loadSharedLists(user);loadInvites(user);await startStateListener(user)});
  window.addEventListener('offline',()=>{if(auth.currentUser)showSyncStatus()});window.addEventListener('online',()=>{if(auth.currentUser){setStatus('Ansluten — synkar ändringar …');pushState()}});setInterval(()=>{if(auth.currentUser)showSyncStatus()},30000);
})();
